apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: ecsoperator.v1.0.0
  namespace: placeholder
  annotations:
    capabilities: Full Lifecycle
    categories: "Storage"
    description: Cloud-native, persistent storage for containers.
    containerImage: ecs/cluster-operator:v1.0.0
    repository: https://github.com/ecs/cluster-operator
    createdAt: 2019-03-25T08:00:00Z
    support: ECS, Inc
    certified: "false"
    alm-examples: |-
      [
        {
          "apiVersion": "dellemc.com/v1",
          "kind": "ECSCluster",
          "metadata": {
            "name": "example-ecs",
            "namespace": "default"
          },
          "spec": {
            "secretRefName": "ecs-api",
            "secretRefNamespace": "default"
          }
        },
        {
          "apiVersion": "dellemc.com/v1",
          "kind": "Job",
          "metadata": {
            "name": "example-job",
            "namespace": "default"
          },
          "spec": {
            "image": "ecs/cluster-operator:latest",
            "args": ["/var/lib/ecs"],
            "mountPath": "/var/lib",
            "hostPath": "/var/lib",
            "completionWord": "done"
          }
        },
        {
          "apiVersion": "dellemc.com/v1",
          "kind": "ECSUpgrade",
          "metadata": {
            "name": "example-upgrade",
            "namespace": "default"
          },
          "spec": {
            "newImage": "ecs/node:latest"
          }
        }
      ]

spec:
  displayName: ECS
  description: |
    ECS is a cloud native, software-defined storage platform that
    transforms commodity server or cloud based disk capacity into
    enterprise-class persistent storage for containers. ECS is ideal for
    deploying databases, message busses, and other mission-critical stateful
    solutions, where rapid recovery and fault tolerance are essential.

    The ECS Operator installs and manages ECS within a cluster.
    Cluster nodes may contribute local or attached disk-based storage into a
    distributed pool, which is then available to all cluster members via a
    global namespace.

    Volumes are available across the cluster so if a container gets moved to
    another node it has immediate access to re-attach its data. Data can be
    protected with synchronous replication. Compression, caching, and QoS are
    enabled by default, and all volumes are thinly-provisioned.

    No other hardware or software is required.

    ECS is free to use up to 100GB of presented Storage, increasing to
    500GB after registration.  For additional capacity and support plans contact
    sales@dellemc.com.

    ## Supported Features

    * **Rapid volume failover** - If a container gets re-scheduled to another
    node, any ECS volumes can be re-attached immediately, irrespective of
    where the data is located within the cluster.

    * **Data protection** - Data is replicated synchronously, up to 6 copies.

    * **Block checksums** - Each block is protected by a checksum which
    automatically detects any corruption of data in the underlying storage
    media.

    * **Thin provisioning** - Only consume the space you need in a storage pool.

    * **Data reduction** - Transparent inline data compression to reduce the
    amount of storage used in a backing store as well as reducing the network
    bandwidth requirements for replication.

    * **In-memory caching** - Speed up access to data even when accessed
    remotely.

    * **Quality of service** - Prioritize data traffic and address the “noisy
    neighbors” problem.

    * **Flexible configuration** - Use labels to automate data placement and
    enforce data policy such as replication. Ideal for compliance and infosec
    teams to enforce policies and rules while still enabling self-service
    storage by developers and DevOps teams.

    * **Access control** - Support multiple namespace – individual users are
    permissioned to specific storage namespaces.

    * **Observability & instrumentation** - Log streams for observability and
    Prometheus support for instrumentation.

    * **Deployment flexibility** - Scale up or scale out storage based on
    application requirements.  Works with any infrastructure – on-premises, VM,
    bare metal or cloud.

    * **Small footprint** - Lightweight container requires minimum 1 core with
    2GB of RAM.  Runs in user-space on any 64-bit Linux with no custom kernel
    modules.

    ## Required Parameters

    * `secretRefName` - the name of a secret that contains two keys for the `apiUsername` and `apiPassword` to be used as api credentials ([documentation](https://docs.dellemc.com/docs/reference/cluster-operator/examples))
    * `secretRefNamespace` - the namespace where the api credentials secret is stored

    ## About ECS

    ECS gives users total control of their own storage environment –
    whether in the cloud or on-premises. Our customers take advantage of storage
    on any platform while maintaining full control of business requirements
    around availability, data mobility, performance, security, data residency
    compliance and business continuity.

  keywords: ['ecs', 'storage', 'persistent storage', 'open source']

  version: 1.0.0
  minKubeVersion: "1.10.0"
  maturity: stable
  maintainers:
  - name: ECS, Inc
    email: support@dellemc.com

  provider:
    name: ECS, Inc

  labels:
    operated-by: ecsoperator

  selector:
    matchLabels:
      operated-by: ecsoperator

  links:
  - name: Documentation
    url: https://docs.dellemc.com/
  - name: ECS Operator Source Code
    url: https://github.com/ecs/cluster-operator

  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAakAAAGpCAYAAAA3LMlbAAAX9klEQVR4nOzdT24bR9438JoX2Uc3GPkEUU5gCSC40Ca2LhAbILS1fQJbJ7CzFQhIvoCsbLQgCERzAjMniOYGygneB+2niIfjkdhNsv/8uvX5AMZMYItdItn97ar+VdX/SwAQlJACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQ1g9dNwD4X5P5+EVK6XlK6SD/2Vv560VK6S6l9HtK6XY6mt112FRozT+6bgA8ZZP5uAiitymlN9+FUpnrlNJv09HstsHmQeeEFHRkMh+/Sil93DCcvvcppXQ2Hc3ua2wahCGkoAOT+fgipfSqppdbpJReT0ezRU2vB2EIKWjZZD5+m3tQdSp6UkeCiqERUtCiyXx8mFL6o6GXL4LqmaE/hkQJOrQkF0lcNHiI4vW/NPj60DohBe15n1Lab/gYh7mUHQZBSEEL8jDf25YOV/fzLuiMkIJ2vG/xWPt6UwyFkIKG5cA4bPmwv7R8PGiEkILmdTH81nYoQiOEFDQoryrRdLHEQ/ZzNSH0mpCCZrX5LOp7Bx0eG2ohpKAhk/n4Q0e9KBgMIQUNyENtb7puB/SdkIJmvN1xdfM6WB6J3rN2H9RsMh/vp5S+dh1S09HM+U3v6UlB/XbdI6oOVkNnEIQU1ChP3I2w2oMdexkEIQU1aWGV80187roBUAchBTXIAfVHgGG+wq3NDxkKIQU7WgmoKJNnz7puANTlh64bAH2Ug+kwpfQ8pfQqSA+q8Gk6mnkexWAIKZ6EyXx8kAsafqoQKIuU0t8ppR8f6B3tBeoxfW+hF8XQmEfBYOXezqu88sPQlycqAupoOpqZwMug6EkxSLkU/OMTCKckoBgyhRMMzmQ+LsLpyxMJqEsBxZDpSTEok/n4Ig/xDd1tSulMkQRDJ6QYjB4E1P13yxWVFWGs/vvi//+Z//tWz4mnQuEEg5CfQX3puh1ZESDXKaXfi1CZjmZ3XTcI+kpI0Xu5iu+vIHOVLlNK7/R0oB6G+xiCCHs3FV5PR7PLrhsBQ6K6jyGIsAOugIIGCCl6LT+L6roX9UlAQTOEFH33S8fHv7cUETRHSNF3XU/YvVYkAc0RUvTdYcfH/1fHx4dBE1KwG3OgoEFCCoCwhBTsputnYjBoQoq+W3R8/OcdHx8GTUjRd12H1Iu8LBPQACFF33VdXVcE1PuO2wCDJaTou+s8obZLbyfzceQtQqC3hBS9lifSXnfdjpTShaCC+tmqg94LtlXHbd6qo+tnZTAIQopBmMzHb1NKH7tux4q7lYm+dTw3u88bKNounidFSDEYPdg+vg7L4c3PAounQEgxKJP5+EtK6UXX7WjJbd7HytJMDJbCCQZlOpq9zFu4PwWHKaWvCjYYMj0pBilvhngRpJiiDZ+mo9m7rhsBddOTYpCmo9l1SulZ3pCw63lUbXibi0dgUPSkeBJyz+pgZa29w2XFXMmPFn//98p//5R7Z3v59aI5UlDBkAgp2EEOvzcBNl9cuksp/Wy3YIbCcB/sYDqaXU9Hs6OiBxNkA8T9lJJhPwZDSEEN8hDbz7ksvGtvum4A1EVIQU3yENvLANuH7ClLZyiEFNRoJai6fiZkM0YGQUhBzfIKEF1PKI5SyAE7EVLQjM8dH3+/4+NDLYQUNMBWHVAPIQVAWEIKGpA3YgR2JKSgGQoXoAZCCprxS8fHjzCpGHYmpKBmk/n4IMAOwQo3GAQhBTXKz6Iuum5HgBJ4qIWQgprkgPojwBYet0rgGQohBTXIQ3wRAirljR5hEH7ougHQZzmc3gR4BrV0bdNDhkRI8WTkQNl7oDz8x9wDuk8p/VnyMj+u9JaWrxfFXUrpddeNgDrZmZdBy1tW/JJSetF1Wxp2n7eO9yyKQdGTYpByr+njE5lUK6AYLIUTDE7uPf3xRALqOqX0TEAxVHpSDEoOqAjzlJp2l1J6Nx3NrrtuCDRJSDEYTyCgFnm5o896TjwVCicYhJV5SlGq7e7zUNyfNSxRtMjb0sOToyfFUFwECqiz6Wj2oetGwBAIKXovD/NFWOmh8Ho6ml123QgYCtV9DMGbrhuQnQkoqJdnUvRafhb1tet25EVdj7puBAyNnhR9F2EliXvLEUEzhBR997zrBqSUfpuOZnddNwKGSEjRd10XTBTh9KnjNsBgCSn6ruuy8zNzmKA5Qgq2d6eaD5olpGB7dsCFhgkp+q6rgoVbvShonpCi77oKKb0oaIGQou9+7+CYRS/qtoPjwpMjpOi7LvZT0ouClggpei1Pom2zV3OpFwXtEVIMQVs9m/uU0ruWjgUIKYYg92zaGPYzcRdaJqQYite5p9OU2+loZvkjaJmQYhByD+eooaC6Sym9bOB1gRJCisGYjmaLBoKqeK2XhvmgG0KKQclB9aymir9voZdfE+iAnXkZrMl8/Cql9D6ltL/hj97nPaI+NNQ0oCIhxeBN5uMXKaVfUkqHawLrPve+frcmH8QhpHhSJvPx3gMbJd7ZWRcAgI0onAAgLCEFQFhCCoCwhBQAYQkpAMISUgCEJaQACEtIARCWkAIgLCEFQFhCCoCwhBQAYQkpAMISUgCE9UPXDSgcn5wepJT2WjjU/c3V+YNbgR+fnO5vsYNrnRY3V+f3u7zA8cnp4TY/d3N1XsdW68s2tPk+Pvp5tu345PRVSunX/J93KaXfIrTt+OT0of2z6lDp+9rxebXzObVqMh9vdX5NR7Pazq91JvNxm+/1Yjqa1fbertNZSOUL6puU0osWD1t8WY4e+bvlVuNdOcrtqyyH+695x9mtL0THJ6fF/yzy8T/veHFt9X3Mbb/O7b5u67jfteEi/96rXhyfnL6s8wZgg/Yc5p2IXzR40ar6fe3yvNr4nFqVL/ov8jm29fk1mY/T6vk1Hc1qu3nJbXzT8Gf9kJ3e2020HlL5zuoiX1jZQr4Iva/5PTzIf94en5wWX76zLi6wW3qRQ6E4+V+32YM5Pjl98UBApTwy8OX45PRZnXfzFdryseMRgd6bzMcH+X1s5PyazMfF9/NsOprtdFM1mY8/dHxj3YpWQyrf+f/R0tDe4OShm4sWep/FyXl4fHJ6nS/6rVxka1B8v74en5wWbb5s+mArn8dj9vJF5F3D7XDjV5PJfFyE09uGD1N8T79M5uPiJvDlpsNmk/n42w3QU/m8WyucyCeSgNrSSsC3OTxaHOuPfOw+ucjPiJr2vsL3+W2T719+7a9P5YLVlOLCP5mPv7YQUKuKz+yv3HPbRN29vNDarO67EFDbWQmoLsLioKdB9THfGDUivx9VL2gfG2yDG78d5Z5JV+fXt2NXDarJfPzY8PJgtRJS+WR6Mslfpzyk9KXjC9Hy+UqfLoZlQ3G72iR4Duvu2QmoWnUVUEvLoKpyUzX4Z1Dfa6sn9WtLxxmiiyAPwvcbvug34bCJHmAOnE1vuj7WHPJGJmqQn0FFGCVY3ow+KodYhLa2qq3CiSpv7G1K6V8Nt+Ou5PibeF5yobpMKf17g9f7r7blKr5NnkEty1z/rvjvf9ywfP1F0aYdq/6K9+XzDj+fcpv/md+bsgv1r/l9qUUOmm2G72orojg+Of2w4cWqiXNr3bn0/bG7sraNeYhtk2dQTZ9fB5P5+NV0NHus6KfKjdFdDedXFVU//521FVJlb+7ZzdX5h5ba8qB84a18QuULxbrf63MNJdxVey7XxcXv5up8qy/OhtVh73e88Py7hvfl288fn5y+qzBUU/cwc5Viice8PT453WkeWg7JNxX/+WU+t1q7oHxv0/OqZVWHzm5zyfhWv0fuAb2v+Czpff7cHlI2olJ8zj+3Ncm2LVGWRfrUdQOiyb2oKsN8r2+uzl/uciEqfvbm6vyoeK0K//xw25Ut6pZL4x+bnL1U2/BIhWKJRYXv8q5FFFV6j9/el5ur89ddBlRkKxN1yxThdLTLqhHT0exuOpoV59bL/Nmss1/0prY81OehBVSKElI9mofTpirP8WqdD5Rfq0pQhXnGmL87aydF1vhcqixgip7dWcmFaNciiirvfScrXfRM1YCqbYQnT96tcn79Utcxh6CtkFo7vJFnyvOfynor101MWM2vWTYTPkRPasWfJX+/c4FBhWKJyyIYcmiWPXfaqogi/0yVoXMBVa4sCG7rDKilHFRlve3HrodlN/PPt2xWaCFCajn5smclzo2puChnk6sYlL32fpNzkKKpUCxxn3tQ3+SgXxcUe1uWEpf1CO8NnVdWFva/NXjss7J/8MhitmU3H4eT+fhii8nBobVVOPF7yUPD5ZyWi7xg6K4W+c/vXS06uqOyAFg0+ayheO28Dt66L/t+mxU+HSsrlvjtgc/jrORCuE0RRZXe9YN328cnp/9/g+Ns4mhdzy0XGLU+t+fm6vwfj/1dhYv43a7r6q0zHc3uJ/PxZck18eD7UJqOZovJfHxXcn0oXvNVXtR2V/fL62jx3ZqOZp2c7630pHJQtPkLHuQP68vxyelfPRxOLDuJfm+hDWXHiNSTKhvm2Pq7V6FY4u6hytR84S4bjq17JYqmp3AMRdmITRvDpdsOUbdRXr7ahsP8Pf1rMh9/zKtztKrNwolGF9lcYz+HVZ8mopZ9EdoI/LJjhAipPOy4toexY6+zLEjWPQh/V6GIos614p5Kz7Zpm8xv3Na20xA+1Tnvb0NvN1nCqS6thVTuTXU5Xv4qDz0MQYSQ6tzKklHrbH1XXKFY4nrdUFceeit7/vDes1iqyiXmrysUUTSlCKiLNntUrW7VcXN1/u745PTvDtefKi4IlwOYO9LGF6SpY/yzhnlWe3mI71WFdm41NFqxWKJ0dODm6vzT8cnpuk3zlsepUpoMy2dTR/kGrYsRjeUQeCs3/a3Pk8rj9z93OAu9Dws0lnXn2+hulx1j2yGHV3mViF3+fMknSZVJrduW6W9TLPGYsjB7VdMEaT2yevyzhWPsFC55d9+fK8zLa8qbtnpTnWwfnyuajvLzhBcppZ9quiM4qHCivujBXWuE+RBlx+jDBOzftpkoXqFY4lvV04bBclsydPgxX3TWKQvF52vmuG17U1hlOsQuFh18l8pusNqYB1h2fpXeBOahvw+T+fhTbvPzmm5g9yq8zl6+lja+uWgnIbWU70RrfU6VLxzrtrbYK8Ix8pDfzdX5bUkp/mGTv0PFYoToE0Zvd1gPsqxYosqzsE0dHJ+cvr25Ol93PpRduF491mvLy15trIUS8ndtf5dyCfj9mmvE/mQ+PtxlKaR1cg+krOK48rmdw+q6wiT8ynIbP5aUyf9U1/HWCbEsUp3yF76spxSiMq1E2QWpyQtH2Wt3VV1U1SKvk7axLbfhqMvaIoo8ArGu17FXc7XgkJUFUJPnV9lQ9X0ezutMEXx5vcF1YdlKld/gQir9XyVh35XNh6jrOcZ/yK9ZtrZcm3M1NnWZJ5huM8y37TYcdaly/LLv9vse7qLchbKCmsMdFnp9VC7fLlvFPtL1q/MRp0GG1ECW7KnyRf1S5wUpv1aVYaxIJ9HSYmXl722fceyyDUddym4+ym4Q9vLKLUM4B5p0XeFZ2EXerr0WOaCq7KYc+SawdYMMqYr7toSWnzeVPZT8tu10HUM8+dnD1won0K4l/Hd5qGWTP1Xs7/IAvkKxRJse7U3l4eyy97/4Xb7WvWX9kOTnOFXW5/symY8/7FrJNpmP31YMqNumnoVtKodq54tJt1I4UXHB1Lr8WiGk+lCZlnJ5adnvspdX1X6T7w43mRe0yXyj1Tbt4vOmBQ05hKsUMxSBfbTlpoJVhvl2/d2Xfi05H8qKKF7nC946yx7V+3xnvu2Fr+ly7IOa1ut8yKKkV/0pD72Vffff55Lry7z01CbXj19ykUTV69/a79gjC882Yb/COdHKUGBb1X2vAs1Put9lZ9Q25YVezyq+d/u5J9Bkb6CTXV7zhNifKgb2xkFVsVjisq7do/PivWXDqsuJ5/91QczVn9cV90Ra7gob5fz7XpPPAI/WhXOu8jur2Ia9Fs6v6wq9qLKbkza1slbkUIf71on4POVR+cIYIVQXXW7xf3N1/rrinIxlUFV6VlexWKLS6hJV5cKesotRWbvKKq+oYDqafQpyTVj0YP7m91p5355iSPXxoeRRx0G1qLBNe+NyUFUZttokqKoUS5w1sHt0lQvSo0UUuT1VtiOn3OuOz69v6/H1bOv3y7ba+9RC6lMPJqH+l3xB6iqoFtuWdDfkZcX3oTSoKhZLLEom2G4lD5tWeca1rohiefMQ5bPppXyxXTs02KDie3DU9byoDVVZOLk2TymkFm2+sXVbCarGlyFZsfWco6ZsGNhlQVXlWUSTW8x8qlKpt656MwfVsw7XwhyEPHn1qOWdGorP7OeeBVThZZsbID6VkLqOdrHdRtH+POR11PDziLsa5hw1Jrep6nYFDwbVBsUSjV388+9RJQTLVqK4z8seeU61o+lo9q6FXtVdHt476tkQ310O1VZviIYeUrf5Yvsy4sV2W8WF8+bq/Fm+KNX58LJ4rSKYnkUfFt1wqOs/gmqDYonGe941FVEsX+ty5XvRt7vzMIqLcO5VHdV8ft3mcHo2Hc3aHBHZ1XJoupNeX1sl6G1f8Bb5WUKTd5Vlv1Pjd7TFRam4288X3V0m3t3WGEplr1Pbd6EIquOT06OKpdgpvz+LXJZdNpGz6e/PqtdVJqAXn3OVm63vvheHDa+xVvYedXmzs9Pnl3sM39qf5ydV2WXhIcVrLGrqNbX5yOI+Ty52wwMADxn6cB8APSakAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGEJKQDCElIAhCWkAAhLSAEQlpACICwhBUBYQgqAsIQUAGH9TwAAAP//uWVl5opI2wgAAAAASUVORK5CYII=
    mediatype: image/png

  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true

  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: ecs-operator
        rules:
        - apiGroups:
          - dellemc.com
          resources:
          - ecsclusters
          - ecsupgrades
          - jobs
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - statefulsets
          - daemonsets
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - list
          - watch
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - list
          - watch
          - get
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          - namespaces
          - serviceaccounts
          - secrets
          - services
          - persistentvolumeclaims
          - persistentvolumes
          verbs:
          - create
          - patch
          - get
          - list
          - delete
          - watch
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          - clusterroles
          - clusterrolebindings
          verbs:
          - create
          - delete
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          - volumeattachments
          - csinodeinfos
          verbs:
          - create
          - delete
          - watch
          - list
          - get
          - update
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
        - apiGroups:
          - csi.storage.k8s.io
          resources:
          - csidrivers
          verbs:
          - create
          - delete
      deployments:
      - name: ecs-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ecs-operator
          template:
            metadata:
              name: ecs-operator
              labels:
                name: ecs-operator
            spec:
              serviceAccountName: ecs-operator
              containers:
              - name: ecs-operator
                command:
                - cluster-operator
                image: ecs/cluster-operator:v1.0.0
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: OPERATOR_NAME
                  value: "cluster-operator"
                ports:
                - containerPort: 8080
                  name: metrics
  customresourcedefinitions:
    owned:
    - name: ecsclusters.dellemc.com
      version: v1
      kind: ECSCluster
      displayName: ECS Cluster
      description: ECS Cluster installs ECS in the cluster. It contains all the configuration for setting up a ECS cluster and also shows the status of the running ECS cluster.
      specDescriptors:
      - description: The name of the secret object that stores the api credentials.
        displayName: Cluster Secret
        path: secretRefName
      - description: The name of the namespace where the secret object that stores the api credentials exists.
        displayName: Cluster Secret Namespace
        path: secretRefNamespace
      statusDescriptors:
      - description: Set of nodes that are part of the ECS Cluster.
        displayName: Nodes
        path: nodes
      - description: The status of each of the members of ECS Cluster.
        displayName: Member Status
        path: members
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: The current status of the ECS Cluster.
        displayName: Status
        path: phase
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.phase
      - description: Ready Nodes
        displayName: Ready
        path: ready
    - name: jobs.dellemc.com
      version: v1
      kind: Job
      displayName: ECS Job
      description: ECS Job creates special pods that run on all the node and perform an administrative task. This could be used for cluster maintenance tasks.
    - name: ecsupgrades.dellemc.com
      version: v1
      kind: ECSUpgrade
      displayName: ECS Upgrade
      description: ECS Upgrade automatically upgrades an existing ECS cluster as per the upgrade configuration.
