java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar
java -jar build/libs/aws-put-metrics-workshop-1.0.jar

