---
s3:
  endpoint: https://object.ecstestdrive.com
  access_key: <your access key>
  secret_Key: <your secret key>
  region: us-east-1
  demo_bucket_name: workshop-bucket
# Empty for no logging, or
# LogDebugWithSigning/LogDebugWithHTTPBody/LogDebugWithRequestRetries/LogDebugWithRequestErrors
loglevel:
