apiVersion: dellemc.com/v1
kind: Job
metadata:
  name: example-job
spec:
  image: nautilus/cleanup:v0.0.2
  args: ["/var/lib/nautilus"]
  mountPath: "/var/lib"
  hostPath: "/var/lib"
  completionWord: "done"
