kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nautilus-tier2
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: "nautilus.nautilus.io/v1alpha1"
kind: "NautilusCluster"
metadata:
  name: "nautilus"
spec:
  zookeeperUri: zk-client:2181

  externalAccess:
    enabled: true
    type: LoadBalancer

  bookkeeper:
    image:
      repository: nautilus/bookkeeper
      tag: latest
      pullPolicy: IfNotPresent

    replicas: 3

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

    autoRecovery: true

  nautilus:
    controllerReplicas: 1
    nodeReplicas: 3

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi

    image:
      repository: nautilus/nautilus
      tag: latest
      pullPolicy: IfNotPresent

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: nautilus-tier2
