apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nautilusclusters.nautilus.nautilus.io
spec:
  group: nautilus.nautilus.io
  names:
    kind: NautilusCluster
    listKind: NautilusClusterList
    plural: nautilusclusters
    singular: nautiluscluster
  additionalPrinterColumns:
  - name: Members
    type: integer
    description: The number nautilus members running
    JSONPath: .status.replicas
  - name: Ready Members
    type: integer
    description: The number nautilus members ready
    JSONPath: .status.readyReplicas
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}