apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautilus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nautilus-operator
  template:
    metadata:
      labels:
        name: nautilus-operator
    spec:
      serviceAccountName: nautilus-operator
      containers:
        - name: nautilus-operator
          image: nautilus/nautilus-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - nautilus-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nautilus-operator"
