apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecs-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ecs-operator
  template:
    metadata:
      labels:
        name: ecs-operator
    spec:
      serviceAccountName: ecs-operator
      containers:
        - name: ecs-operator
          image: ecs/ecs-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - ecs-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ecs-operator"
