kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ecscluster-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: ecscluster-operator-sa
  namespace: ecs-operator
roleRef:
  kind: ClusterRole
  name: ecs-operator
  apiGroup: rbac.authorization.k8s.io
