kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecs-operator
subjects:
- kind: ServiceAccount
  name: ecs-operator
roleRef:
  kind: Role
  name: ecs-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ecs-operator
subjects:
- kind: ServiceAccount
  name: ecs-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: ecs-operator
  apiGroup: rbac.authorization.k8s.io
